on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: |
          echo "setup something"
          echo "${{ toJSON(github) }}"
  job1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: |
          echo "do something1"
  job2:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      output_via_command: ${{ steps.step.outputs.command_reesult }}
      output_via_env: ${{ env.ENV_RESULT }}
    steps:
      - name: step
        run: |
          echo "do something2"
          echo "::set-output name=command_reesult::1234"
          echo "ENV_RESULT=5678" >> $GITHUB_ENV
  job3:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: |
          echo "do something3"
          exit 1
  job4:
    needs: setup
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: |
          echo "skip always"
  check-result:
    needs: [job1, job2, job3, job4]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: |
          echo "check something"
          echo "${{ toJSON(needs) }}"
          echo "env.ENV_RESULT=${{ env.ENV_RESULT }}"
